source 'https://rubygems.org'

ruby File.read(".ruby-version").strip

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'fix-db-schema-conflicts', path: '../..'
